name: Matt Holliday Photography
favicon: null
layout_spectrum: 0.50671
typography_spectrum: 0.8383338954299688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.03779298858717084
  lightness: 0.6016126982867718
  saturation: 0.19857605709694326
  rhythmicContrast: 0.5025413688272238
purpose: []
